"""add actual start

Revision ID: 1a9c1c9da008
Revises: 29394abcb8bc
Create Date: 2021-10-18 00:12:10.044432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a9c1c9da008'
down_revision = '29394abcb8bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_start', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumers', schema=None) as batch_op:
        batch_op.drop_column('actual_start')

    # ### end Alembic commands ###
