"""add webhook

Revision ID: 4627f2fdba72
Revises: 1a9c1c9da008
Create Date: 2021-10-18 00:28:28.457115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4627f2fdba72'
down_revision = '1a9c1c9da008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumers', schema=None) as batch_op:
        batch_op.drop_column('webhook')

    # ### end Alembic commands ###
