"""add payment note

Revision ID: 648c0c21adf1
Revises: 7d17158147a0
Create Date: 2021-10-17 23:24:45.664175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648c0c21adf1'
down_revision = '7d17158147a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'notes')
    # ### end Alembic commands ###
