"""init

Revision ID: 7d17158147a0
Revises: 
Create Date: 2021-10-17 22:58:53.983140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d17158147a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('paypal_email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_consumers'))
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paypal_transaction', sa.String(), nullable=True),
    sa.Column('consumer_name', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('months_amount', sa.Integer(), nullable=True),
    sa.Column('euros_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['consumer_name'], ['consumers.name'], name=op.f('fk_payments_consumer_name_consumers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('paypal_transaction', name=op.f('uq_payments_paypal_transaction'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('consumers')
    # ### end Alembic commands ###
